highlighter: rouge
safe: true
# source: <your pages repo>
# destination: <the build dir>
markdown: kramdown
lsi: false
# BaseUrl may not be RosaLuna or the images do not display correctly!
baseurl: /
plugins:
  - jekyll-seo-tag
